name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: JavierMartinAlonso1980
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Push to output branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan output-branch
          git --git-dir=.git --work-tree=dist add -A
          git commit -m "Update snake animation"
          git push -f origin HEAD:output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
